spring:
  application:
    name: foo

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/foo
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

snowflake:
  epoch: 2025-08-12T00:00:00Z
  datacenter-id: 1
  server-id: 1